name: Build Windows

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Flet
        run: pip install flet flet-charts flet-cli

      - name: Build EXE
        run: flet build windows --yes

      - name: Upload EXE
        uses: actions/upload-artifact@v4
        with:
          name: app-windows
          path: build/windows/*